---
title: "PEP: A metric for evaluating the importance of tackles"
author: "Robert Bajons, Jan-Ole Koslik, Rouven Michels, Marius Ötting"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> "Football is two things. It's blocking and tackling."

> *Vince Lombardi*

## Introduction

Although this citation dates back several decades --- and American Football has of course changed since then --- tackling remains an integral aspect of the game. In contrast to decision-making scenarios faced by players, such as a quarterback's selection of a target for a pass, the decision for a tackle is more straightforward: a defense player should always promptly tackle the ball carrier.

When assessing players' tackles, one is usually interested in a hypothetical scenario: the potential outcome if a player were to miss a tackle. 
Essentially, this involves quantifying the yards saved by a defensive player. Ideally, albeit impractically, running a play twice --- once with the defense player executing the tackle and a second time without --- would allow a direct comparison of the yardage gained by the ball carrier, thus enabling to evaluate the impact of the defensive player's tackle.

Given the impracticability of such a hypothetical scenario, our approach involves approximating it by predicting the yardline of the ongoing play twice. First, we consider the inclusion of the closest defender who executed the tackle, and in a next step, we exclude this player. * Based on these predicted yardlines, we compute the expected points (EP) gained through the tackle. This approach enables us to evaluate players in terms of the importance of their tacklings.

* Hier sollten wir noch etwas mehr bewerben, dass wir nicht einfach die gesaften yards rauskriegen sondern einen tackle value auf expected points Skala. Das ist ja ein sehr wichtiger Pluspunkt bei uns.

## Data

To accurately predict the yardline at the end of any given play we needed to create several features derived from the tracking data. More specifically, we conducted the following feature preprocessing:

#### Change of coordinate system
We transformed the coordinate system by 

* redefining the x variable as the x distance to the endzone (such that all play directions are from right to left and the relevant endzone is at zero),
* centering the y-variable such that the center of the field is at zero,
* changing the direction variable, such that zero degrees represents heading straight towards the relevant endzone.

#### Response variable: Yards to be gained
For each play, we defined the x position of the ball carrier in the last frame as the end-of-play yard line. The response variable we aim to predict is now *yards to be gained* as the difference of the x position of the ballcarrier in a given frame to the end-of-play yard line.

#### Feature engineering
For all players and the ball carrier we use the features already contained in the tracking data, namely x- and y-coordinates, speed, acceleration, distance covered, orientation and direction.

For all players except the ball carrier we further compute

* euclidean distance to ball carrier,
* x-distance to ball carrier,
* y-distance to ball carrier.

For defensive players only, we additionally compute the absolute difference of the defender direction and the angle of the shortest segement between the defender and the ball carrier.

Subsequently we order all players (in each frame) with respect to their euclidean distance to the ball carrier and standardise all features.

We did not rely on the event column to identify tackle events, but defined as the tackle event the frame in which the tacklers distance to the ballcarrier is minimal within a given play.

- Plays rausnehmen

...add an example play to illustrate the "what if" scenario...
Hier die end of play yardline und "yards to be gained" einzeichnen.

Animation

## Analysis

Our analysis comprises four steps:

1. **Model Training:** We train a model designed to predict the end-of-play yardline (see Yurko...). The model uses the previously described features, only including the 10 closest defenders. While accounting for the time-series nature of the data by using e.g. a transformer architecture, we do not only want to obtain a point estimate for the yard line at the end of the play. Therefore, and to account for potential non-linear and interaction effects and to end up with a conditional density estimator $\hat{f}(y \mid x)$, we consider a random forest comprising 1000 individual trees.

RMSE und MAE reporten.

2. **Tackler Replacement Procedure:** For each tackle, we systematically remove the closest defender at the tackle moment and replaced them with the second closest (and so forth). 

3. **Yardline Prediction:** The evaluation of tackles involves the use of an EP model with the following features: .... Using our random forest, we predict the end-of-play yardline across the 1000 trees and consider these predictions as inputs for the EP model. 

Animation mit Dichteschätzung

4. **Tackle Evaluation:** We set up an own EP model (similar to nflfastR, ...) and calculate the EPs for all 1000 predictions and average the outcomes (because of integral calculations, Monte Carlo approximation). 
Es gibt zwei Möglichkeiten (echte + expected mit full player) einen Tackle Value zu berechnen, wir nehmen Möglichkeit 2 
This process yields the tackle's value *PEP* (for prevented Expected Points) with the respective tackler excluded from the data set. 

Causal inference Ansatz, aber auf g(y) also EP Ebene.

$$
\text{E}(g(y)) = \int_{0}^\infty g(y) \: \hat{f} (y \mid x) \: dy
$$
Instead of a two-step procedure where we first obtain a density estimate via kernel density estimation from the individual tree predictions to then integrate numerically, we treat the tree-predictions $\hat{y}_1, \dots, \hat{y}_{1000}$ as samples from the conditional density and approximate the above expectation via the Monte Carlo estimate
$$
\frac{1}{1000} \sum_{i=1}^{1000} g(\hat{y}_i).
$$

## Player evaluation

## Discussion

In this contribution, we developed a metric "PEP" for quantifying the value of a tackle. It allows practitioners to assess players, particularly in terms of their tackling abilities. 
However, there are a few drawbacks that need to be taken into account during the evaluation process. Important considerations are the position and the defensive playing styles of teams. Cornerbacks and safeties are often more capable of making "touchdown-saving tackles", resulting in their values typically being higher. Furthermore, safeties who engage in riskier defensive strategies, such as those employed by Brian Flores, receive less support of their teammates in the backfield, which is why their metrics may be higher. 
When taking such aspects into account, however, the metric we have developed can serve as an additional puzzle piece in the overall assessment of (defensive) players and might gain practical relevance in the process of scouting players and opponents.

Future research

## Code

...link to GitHub...

## References

Yurko, nflfastR

